# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: KashishNaresh.CollabFS
PackageVersion: 1.0.0
InstallerType: portable
Commands:
- collab
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kashish-naresh/collabfs/releases/download/v1.0.0/collabfs-win.exe
  InstallerSha256: 627B2E5D50C14D72B5D7A91C2AB73F3C79A3D84AAFD59D97839BA981C562FF96
ManifestType: installer
ManifestVersion: 1.10.0
