# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: KashishNaresh.CollabFS
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Kashish Chaudhary
PublisherUrl: https://github.com/kashish-naresh/collabfs
PublisherSupportUrl: https://github.com/kashish-naresh/collabfs/issues
Author: Kashish Chaudhary
PackageName: CollabFS
PackageUrl: https://github.com/kashish-naresh/collabfs
License: MIT License
LicenseUrl: https://github.com/kashish-naresh/collabfs/blob/main/LICENSE
Copyright: Copyright (c) 2025 KashishNaresh
CopyrightUrl: https://github.com/kashish-naresh/collabfs/blob/main/LICENSE
ShortDescription: Realtime sync collaboration on a project
Description: CollabFS allows anyone to colloborate on a project, changes are synced in realtime.
Moniker: collabfs
Tags:
- collabfs
ReleaseNotes: First Winget of CollabFS
InstallationNotes: 'To start : collab start --name <you-name> and To Join : collab join --session <session-ID> --name <your-name>'
ManifestType: defaultLocale
ManifestVersion: 1.10.0
